"""
GridGuard FastAPI backend.

Endpoints:
  GET  /health              — system status + calibration state
  GET  /sites               — all configured DMV sites
  GET  /sites/{site_id}     — single site detail
  GET  /forecast            — predict generation for a time window
  POST /forecast            — predict for a single interval (legacy)
  GET  /anomalies           — list anomalous intervals
  GET  /events              — anomaly intervals grouped into events
  GET  /events/{event_id}   — single event detail
  GET  /explain             — SHAP contributors for a timestamp
  GET  /metrics             — model comparison table
  GET  /demo/scenario       — the scripted June 15 GMU demo event

Run locally:
    uvicorn gridguard.api.main:app --reload --port 8000

Design notes:
  - Models and test data are loaded once at startup (lifespan event).
  - Residual calibration stats are loaded from artifacts/models/residual_stats.json
    (generated by 'make demo-reset') so anomaly thresholds are never contaminated
    by test-set statistics.
  - No database — state lives in memory for the demo.
  - CORS origins are controlled by the ALLOWED_ORIGINS environment variable.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from datetime import datetime, date
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from gridguard import __version__
from gridguard.anomaly.detect import (
    _load_residual_stats,
    detect_anomalies,
)
from gridguard.anomaly.events import group_anomaly_events
from gridguard.api.schemas import (
    AnomalyRecord,
    AnomalyResponse,
    EventRecord,
    EventsResponse,
    ExplainContributor,
    ExplainResponse,
    ForecastRequest,
    ForecastResponse,
    HealthResponse,
    MetricsResponse,
    ModelMetrics,
    SiteRecord,
    SitesResponse,
    DemoScenarioResponse,
)
from gridguard.config import settings
from gridguard.features.engineer import FEATURE_COLS, build_features
from gridguard.models.evaluate import compare_models, get_X_y
from gridguard.models.train import load_model

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# App state — loaded once at startup
# ---------------------------------------------------------------------------

_state: dict = {
    "models": {},           # lag-aware forecasting models (for /forecast, /metrics)
    "anomaly_model": None,  # weather-only anomaly detector (for /anomalies, /events)
    "test_df": None,
    "anomaly_df": None,
    "events_df": None,
    "metrics_df": None,
    "best_model_name": "xgboost",
    "residual_stats": None,
}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load models, calibration stats, and pre-compute anomalies on startup."""
    logger.info("Loading artifacts …")

    model_dir = Path(settings.model_dir)
    processed_dir = Path(settings.data_processed_dir)

    _state["residual_stats"] = _load_residual_stats(model_dir)
    if _state["residual_stats"]:
        logger.info("Loaded residual calibration stats (%d hour buckets)", len(_state["residual_stats"]))
    else:
        logger.warning("No residual_stats.json found — run 'make demo-reset' first.")

    if not model_dir.exists():
        logger.warning("No model artifacts found. Run 'make demo-reset' first.")
        yield
        return

    from gridguard.models.baseline import ALL_MODELS

    # Load lag-aware forecasting models (for /forecast and /metrics)
    for name in ALL_MODELS:
        try:
            _state["models"][name] = load_model(name)
            logger.info("Loaded forecasting model: %s", name)
        except FileNotFoundError:
            logger.warning("Forecasting model not found: %s (skip)", name)

    # Load the dedicated weather-only anomaly detector (for /anomalies and /events).
    # This model is trained WITHOUT lag features so it can't mask persistent degradation.
    try:
        _state["anomaly_model"] = load_model("anomaly_detector")
        logger.info("Loaded anomaly_detector (weather-only, healthy-data trained)")
    except FileNotFoundError:
        logger.warning(
            "anomaly_detector.pkl not found — run 'make demo-reset'. "
            "Falling back to best forecasting model (lag leakage risk)."
        )
        # Graceful fallback so the API starts in environments without artifacts
        _state["anomaly_model"] = (
            _state["models"].get("xgboost")
            or next(iter(_state["models"].values()), None)
        )

    test_path = processed_dir / "test_df.parquet"

    if test_path.exists():
        test_df = pd.read_parquet(test_path)
        _state["test_df"] = test_df

        anomaly_model = _state["anomaly_model"]
        if anomaly_model is not None:
            _state["anomaly_df"] = detect_anomalies(
                test_df,
                anomaly_model,
                residual_stats=_state["residual_stats"],
            )
            _state["events_df"] = group_anomaly_events(_state["anomaly_df"])

        # Metrics compare all lag-aware forecasting models on the held-out test set
        if _state["models"]:
            X_test, y_test = get_X_y(test_df)
            forecast_models = {k: v for k, v in _state["models"].items() if k != "persistence" or True}
            _state["metrics_df"] = compare_models(forecast_models, X_test, y_test)
            _state["best_model_name"] = _state["metrics_df"].iloc[0]["model"]

    logger.info("Startup complete. Best model: %s", _state["best_model_name"])
    yield


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

def _parse_origins(raw: str) -> list[str]:
    if raw.strip() == "*":
        return ["*"]
    return [o.strip() for o in raw.split(",") if o.strip()]


app = FastAPI(
    title="GridGuard DMV API",
    description=(
        "Open-source ML system for forecasting solar generation and detecting underperformance "
        "in DC/Northern Virginia campus-style solar assets. "
        "Data is synthetic deterministic demo unless real telemetry is configured."
    ),
    version=__version__,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_parse_origins(settings.allowed_origins),
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _require_data(name: str = "Data"):
    if _state["anomaly_df"] is None:
        raise HTTPException(503, f"{name} not loaded. Run 'make demo-reset && make api'.")


def _filter_by_time(df: pd.DataFrame, start: Optional[str], end: Optional[str]) -> pd.DataFrame:
    ts_col = "timestamp" if "timestamp" in df.columns else "start_time"
    if start:
        df = df[df[ts_col] >= pd.Timestamp(start)]
    if end:
        df = df[df[ts_col] <= pd.Timestamp(end)]
    return df


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@app.get("/health", response_model=HealthResponse)
def health():
    return HealthResponse(
        status="ok",
        model_loaded=bool(_state["models"]),
        data_rows=len(_state["test_df"]) if _state["test_df"] is not None else 0,
        version=__version__,
        residual_calibration_loaded=_state["residual_stats"] is not None,
    )


@app.get("/sites", response_model=SitesResponse)
def sites_list():
    """Return all configured DMV sites with geospatial metadata."""
    from gridguard.sites.registry import load_sites
    sites_dict = load_sites()
    records = [
        SiteRecord(
            site_id=s.site_id,
            name=s.name,
            region=s.region,
            latitude=s.latitude,
            longitude=s.longitude,
            capacity_kw=s.capacity_kw,
            notes=s.notes,
        )
        for s in sites_dict.values()
    ]
    return SitesResponse(sites=records, total=len(records))


@app.get("/sites/{site_id}", response_model=SiteRecord)
def site_detail(site_id: str):
    """Return metadata for a single site."""
    from gridguard.sites.registry import load_sites
    sites = load_sites()
    if site_id not in sites:
        raise HTTPException(404, f"Site '{site_id}' not found.")
    s = sites[site_id]
    return SiteRecord(
        site_id=s.site_id,
        name=s.name,
        region=s.region,
        latitude=s.latitude,
        longitude=s.longitude,
        capacity_kw=s.capacity_kw,
        notes=s.notes,
    )


@app.post("/forecast", response_model=ForecastResponse)
def forecast_post(req: ForecastRequest):
    """Predict expected AC power for a single 15-minute interval."""
    model_name = _state["best_model_name"]
    model = _state["models"].get(model_name)
    if model is None:
        raise HTTPException(503, "Models not loaded. Run 'make demo-reset' first.")

    row = pd.DataFrame(
        [
            {
                "timestamp": req.timestamp,
                "irradiance_wm2": req.irradiance_wm2,
                "temperature_c": req.temperature_c,
                "wind_speed_ms": req.wind_speed_ms,
                "ac_power_kw": 0.0,
            }
        ]
    )
    row = build_features(row, include_lags=False)
    row["ac_power_lag1"] = req.ac_power_lag1
    row["ac_power_lag4"] = req.ac_power_lag4

    present = [c for c in FEATURE_COLS if c in row.columns]
    predicted_kw = float(np.clip(model.predict(row[present]), 0, None)[0])

    return ForecastResponse(
        timestamp=req.timestamp,
        predicted_kw=round(predicted_kw, 4),
        model_name=model_name,
    )


@app.get("/forecast", response_model=list[ForecastResponse])
def forecast_range(
    site_id: Optional[str] = Query(default=None),
    start: Optional[str] = Query(default=None, description="ISO 8601 start datetime"),
    end: Optional[str] = Query(default=None, description="ISO 8601 end datetime"),
    limit: int = Query(default=500, le=5000),
):
    """Return expected-generation forecast for a time window from the test dataset."""
    _require_data("Forecast data")
    adf = _state["anomaly_df"].copy()

    if site_id and "site_id" in adf.columns:
        adf = adf[adf["site_id"] == site_id]
    adf = _filter_by_time(adf, start, end)
    adf = adf.head(limit)

    return [
        ForecastResponse(
            timestamp=row["timestamp"],
            predicted_kw=round(float(row["predicted_kw"]), 4),
            model_name=_state["best_model_name"],
        )
        for _, row in adf.iterrows()
    ]


@app.get("/anomalies", response_model=AnomalyResponse)
def anomalies(
    site_id: Optional[str] = Query(default=None),
    start: Optional[str] = Query(default=None, description="ISO 8601 start datetime"),
    end: Optional[str] = Query(default=None, description="ISO 8601 end datetime"),
    limit: int = Query(default=200, le=5000),
    only_anomalies: bool = Query(default=True),
):
    """Return anomalous intervals from the test dataset."""
    _require_data()
    adf = _state["anomaly_df"].copy()

    if site_id and "site_id" in adf.columns:
        adf = adf[adf["site_id"] == site_id]
    adf = _filter_by_time(adf, start, end)

    total_anomalies = int(adf["is_anomaly"].sum())
    total_lost = float(adf["lost_energy_kwh"].sum())

    if only_anomalies:
        adf = adf[adf["is_anomaly"]]
    adf = adf.head(limit)

    records = [
        AnomalyRecord(
            timestamp=row["timestamp"],
            actual_kw=round(float(row["ac_power_kw"]), 4),
            predicted_kw=round(float(row["predicted_kw"]), 4),
            residual_kw=round(float(row["residual_kw"]), 4),
            residual_sigma=round(float(row.get("residual_sigma", 0) or 0), 3),
            lost_energy_kwh=round(float(row["lost_energy_kwh"]), 4),
            is_anomaly=bool(row["is_anomaly"]),
        )
        for _, row in adf.iterrows()
    ]

    return AnomalyResponse(
        total_anomalies=total_anomalies,
        total_lost_kwh=round(total_lost, 2),
        records=records,
    )


@app.get("/events", response_model=EventsResponse)
def events(
    site_id: Optional[str] = Query(default=None),
    start: Optional[str] = Query(default=None, description="ISO 8601 start datetime"),
    end: Optional[str] = Query(default=None, description="ISO 8601 end datetime"),
    limit: int = Query(default=50, le=500),
    severity: Optional[str] = Query(default=None, description="Filter: low, medium, high"),
):
    """Return anomaly intervals grouped into contiguous events."""
    edf = _state["events_df"]
    if edf is None:
        raise HTTPException(503, "Event data not loaded. Run 'make demo-reset' first.")

    edf = edf.copy()

    if site_id and "site_id" in edf.columns:
        edf = edf[edf["site_id"] == site_id]
    if severity:
        if severity not in ("low", "medium", "high"):
            raise HTTPException(400, "severity must be one of: low, medium, high")
        edf = edf[edf["severity"] == severity]
    edf = _filter_by_time(edf, start, end)

    total_events = len(edf)
    total_lost = float(edf["total_lost_kwh"].sum())
    edf = edf.head(limit)

    event_records = [
        EventRecord(
            event_id=int(row["event_id"]),
            start_time=row["start_time"],
            end_time=row["end_time"],
            duration_minutes=int(row["duration_minutes"]),
            interval_count=int(row["interval_count"]),
            total_lost_kwh=round(float(row["total_lost_kwh"]), 3),
            max_residual_sigma=round(float(row["max_residual_sigma"]), 3),
            mean_actual_kw=round(float(row["mean_actual_kw"]), 4),
            mean_predicted_kw=round(float(row["mean_predicted_kw"]), 4),
            severity=row["severity"],
            explanation=str(row.get("explanation", "")),
            site_id=row.get("site_id"),
        )
        for _, row in edf.iterrows()
    ]

    return EventsResponse(
        total_events=total_events,
        total_lost_kwh=round(total_lost, 2),
        events=event_records,
    )


@app.get("/events/{event_id}", response_model=EventRecord)
def event_detail(event_id: int):
    """Return a single event by ID."""
    edf = _state["events_df"]
    if edf is None:
        raise HTTPException(503, "Event data not loaded. Run 'make demo-reset' first.")

    match = edf[edf["event_id"] == event_id]
    if match.empty:
        raise HTTPException(404, f"Event {event_id} not found.")

    row = match.iloc[0]
    return EventRecord(
        event_id=int(row["event_id"]),
        start_time=row["start_time"],
        end_time=row["end_time"],
        duration_minutes=int(row["duration_minutes"]),
        interval_count=int(row["interval_count"]),
        total_lost_kwh=round(float(row["total_lost_kwh"]), 3),
        max_residual_sigma=round(float(row["max_residual_sigma"]), 3),
        mean_actual_kw=round(float(row["mean_actual_kw"]), 4),
        mean_predicted_kw=round(float(row["mean_predicted_kw"]), 4),
        severity=row["severity"],
        explanation=str(row.get("explanation", "")),
        site_id=row.get("site_id"),
    )


@app.get("/explain", response_model=ExplainResponse)
def explain(
    timestamp: datetime = Query(..., description="Timestamp of the interval to explain (ISO 8601)"),
):
    """Return SHAP feature contributions for the model's prediction at a given timestamp."""
    _require_data()
    adf = _state["anomaly_df"]

    ts = pd.Timestamp(timestamp)
    mask = adf["timestamp"] == ts
    if not mask.any():
        mask = (adf["timestamp"] - ts).abs() <= pd.Timedelta("1min")
    if not mask.any():
        raise HTTPException(
            404,
            f"Timestamp {timestamp} not found in test dataset. "
            f"Range: {adf['timestamp'].min().isoformat()} – {adf['timestamp'].max().isoformat()}",
        )

    row_df = build_features(adf[mask].head(1).copy())
    present = [c for c in FEATURE_COLS if c in row_df.columns]
    X_row = row_df[present]

    model_name = _state["best_model_name"]
    model = _state["models"].get(model_name)
    if model is None:
        raise HTTPException(503, "Model not loaded.")

    predicted_kw = float(np.clip(model.predict(X_row), 0, None)[0])

    try:
        from gridguard.explainability.shap_explain import explain_anomaly
        shap_df = explain_anomaly(model, X_row, top_n=len(present))
        contributors = [
            ExplainContributor(
                feature=r["feature"],
                feature_value=round(float(r["feature_value"]), 4),
                shap_value=round(float(r["shap_value"]), 4),
                direction="positive" if r["shap_value"] >= 0 else "negative",
            )
            for _, r in shap_df.iterrows()
        ]
        shap_available = True
    except Exception as exc:
        logger.warning("SHAP explanation failed: %s", exc)
        contributors = []
        shap_available = False
        if hasattr(model, "feature_importances_"):
            importances = model.feature_importances_
            for feat, imp in sorted(zip(present, importances), key=lambda x: -abs(x[1])):
                val = float(X_row[feat].iloc[0])
                contributors.append(
                    ExplainContributor(
                        feature=feat,
                        feature_value=round(val, 4),
                        shap_value=round(float(imp), 6),
                        direction="positive",
                    )
                )

    return ExplainResponse(
        timestamp=ts,
        predicted_kw=round(predicted_kw, 4),
        contributors=contributors[:10],
        model_name=model_name,
        shap_available=shap_available,
    )


@app.get("/metrics", response_model=MetricsResponse)
def metrics():
    """Return performance metrics for all trained models."""
    mdf = _state["metrics_df"]
    if mdf is None:
        raise HTTPException(503, "Metrics not computed. Run 'make demo-reset' first.")

    model_metrics = [
        ModelMetrics(
            model=row["model"],
            mae_kw=row["mae_kw"],
            rmse_kw=row["rmse_kw"],
            mape_pct=row["mape_pct"],
            r2=row["r2"],
        )
        for _, row in mdf.iterrows()
    ]
    return MetricsResponse(
        models=model_metrics,
        best_model=_state["best_model_name"],
    )


@app.get("/demo/scenario", response_model=DemoScenarioResponse)
def demo_scenario():
    """Return metadata for the scripted June 15 GMU Fairfax demo event.

    This is a deterministic synthetic underperformance window designed for
    demos and presentations. Run 'make demo-reset' to regenerate it.
    """
    edf = _state["events_df"]
    adf = _state["anomaly_df"]

    # Find the June 15 event by looking for the scripted window
    demo_date = pd.Timestamp("2023-06-15").date()
    demo_event_id = None
    demo_event = None

    if edf is not None and not edf.empty:
        june15_events = edf[edf["start_time"].dt.date == demo_date]
        if not june15_events.empty:
            # Pick the event with the most lost energy on that day
            idx = june15_events["total_lost_kwh"].idxmax()
            row = june15_events.loc[idx]
            demo_event_id = int(row["event_id"])
            demo_event = EventRecord(
                event_id=demo_event_id,
                start_time=row["start_time"],
                end_time=row["end_time"],
                duration_minutes=int(row["duration_minutes"]),
                interval_count=int(row["interval_count"]),
                total_lost_kwh=round(float(row["total_lost_kwh"]), 3),
                max_residual_sigma=round(float(row["max_residual_sigma"]), 3),
                mean_actual_kw=round(float(row["mean_actual_kw"]), 4),
                mean_predicted_kw=round(float(row["mean_predicted_kw"]), 4),
                severity=row["severity"],
                explanation=str(row.get("explanation", "")),
                site_id=row.get("site_id"),
            )

    # Pull anomaly records for the demo window
    demo_anomalies: list[AnomalyRecord] = []
    if adf is not None:
        window = adf[adf["timestamp"].dt.date == demo_date]
        for _, row in window.iterrows():
            demo_anomalies.append(
                AnomalyRecord(
                    timestamp=row["timestamp"],
                    actual_kw=round(float(row["ac_power_kw"]), 4),
                    predicted_kw=round(float(row["predicted_kw"]), 4),
                    residual_kw=round(float(row["residual_kw"]), 4),
                    residual_sigma=round(float(row.get("residual_sigma", 0) or 0), 3),
                    lost_energy_kwh=round(float(row["lost_energy_kwh"]), 4),
                    is_anomaly=bool(row["is_anomaly"]),
                )
            )

    return DemoScenarioResponse(
        data_label="Deterministic synthetic GMU Fairfax PV demo — not real sensor data",
        demo_date="2023-06-15",
        site_id="gmu_fairfax",
        site_name="GMU Fairfax Campus Solar Array",
        event=demo_event,
        anomaly_records=demo_anomalies,
        jump_to_event_id=demo_event_id,
        recommended_actions=[
            "Inspect inverter logs for fault codes between 09:00–12:30",
            "Check for partial shading from nearby construction or tree growth",
            "Compare with neighboring string-level power data",
            "Verify irradiance sensor reading against satellite-derived GHI estimate",
            "Schedule on-site inspection if degradation persists beyond 48 h",
        ],
    )
