"""
GridGuard FastAPI backend.

Endpoints:
  GET  /health          — system status + calibration state
  POST /forecast        — predict generation for a single interval
  GET  /anomalies       — list anomalous intervals from the test dataset
  GET  /events          — anomaly intervals grouped into contiguous events
  GET  /explain         — SHAP contributors for a given timestamp
  GET  /metrics         — model comparison table

Run locally:
    uvicorn gridguard.api.main:app --reload --port 8000
    # API docs: http://localhost:8000/docs

Design notes:
  - Models and test data are loaded once at startup (lifespan event).
  - Residual calibration stats are loaded from artifacts/models/residual_stats.json
    (generated by 'make train') so anomaly thresholds are never contaminated by
    test-set statistics.
  - No database — state lives in memory for the demo. For production, back this
    with a time-series DB (TimescaleDB or DuckDB) and stream live sensor data.

TODO: Add authentication (API key header) before exposing externally.
TODO: Add rate limiting middleware.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from gridguard import __version__
from gridguard.anomaly.detect import (
    _load_residual_stats,
    detect_anomalies,
)
from gridguard.anomaly.events import group_anomaly_events
from gridguard.api.schemas import (
    AnomalyRecord,
    AnomalyResponse,
    EventRecord,
    EventsResponse,
    ExplainContributor,
    ExplainResponse,
    ForecastRequest,
    ForecastResponse,
    HealthResponse,
    MetricsResponse,
    ModelMetrics,
    SiteRecord,
    SitesResponse,
)
from gridguard.config import settings
from gridguard.features.engineer import FEATURE_COLS, build_features
from gridguard.models.evaluate import compare_models, get_X_y
from gridguard.models.train import load_model

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# App state — loaded once at startup
# ---------------------------------------------------------------------------

_state: dict = {
    "models": {},
    "test_df": None,
    "anomaly_df": None,
    "events_df": None,
    "metrics_df": None,
    "best_model_name": "xgboost",
    "residual_stats": None,
}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load models, calibration stats, and pre-compute anomalies on startup."""
    logger.info("Loading artifacts …")

    model_dir = Path(settings.model_dir)
    processed_dir = Path(settings.data_processed_dir)

    # Load residual calibration (training-set stats)
    _state["residual_stats"] = _load_residual_stats(model_dir)
    if _state["residual_stats"]:
        logger.info("Loaded residual calibration stats (%d hour buckets)", len(_state["residual_stats"]))
    else:
        logger.warning("No residual_stats.json found — anomaly thresholds will be uncalibrated.")

    if not model_dir.exists():
        logger.warning("No model artifacts found. Run 'make train' first.")
        yield
        return

    from gridguard.models.baseline import ALL_MODELS

    for name in ALL_MODELS:
        try:
            _state["models"][name] = load_model(name)
            logger.info("Loaded model: %s", name)
        except FileNotFoundError:
            logger.warning("Model artifact not found: %s (skip)", name)

    test_path = processed_dir / "test_df.parquet"
    if test_path.exists():
        test_df = pd.read_parquet(test_path)
        _state["test_df"] = test_df

        best = _state["models"].get("xgboost") or next(iter(_state["models"].values()), None)
        if best:
            _state["anomaly_df"] = detect_anomalies(
                test_df,
                best,
                residual_stats=_state["residual_stats"],
            )
            _state["events_df"] = group_anomaly_events(_state["anomaly_df"])

            X_test, y_test = get_X_y(test_df)
            _state["metrics_df"] = compare_models(_state["models"], X_test, y_test)
            _state["best_model_name"] = _state["metrics_df"].iloc[0]["model"]

    logger.info("Startup complete. Best model: %s", _state["best_model_name"])
    yield


app = FastAPI(
    title="GridGuard DMV API",
    description=(
        "Open-source ML system for forecasting solar generation and detecting underperformance "
        "in DC/Northern Virginia campus-style solar assets. "
        "GMU, NOVA, and DC sites are illustrative; data is synthetic unless real telemetry is configured."
    ),
    version=__version__,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@app.get("/health", response_model=HealthResponse)
def health():
    return HealthResponse(
        status="ok",
        model_loaded=bool(_state["models"]),
        data_rows=len(_state["test_df"]) if _state["test_df"] is not None else 0,
        version=__version__,
        residual_calibration_loaded=_state["residual_stats"] is not None,
    )


@app.post("/forecast", response_model=ForecastResponse)
def forecast(req: ForecastRequest):
    """Predict expected AC power for a single 15-minute interval."""
    model_name = _state["best_model_name"]
    model = _state["models"].get(model_name)
    if model is None:
        raise HTTPException(503, "Models not loaded. Run 'make train' first.")

    row = pd.DataFrame(
        [
            {
                "timestamp": req.timestamp,
                "irradiance_wm2": req.irradiance_wm2,
                "temperature_c": req.temperature_c,
                "wind_speed_ms": req.wind_speed_ms,
                "ac_power_kw": 0.0,
            }
        ]
    )
    row = build_features(row, include_lags=False)
    row["ac_power_lag1"] = req.ac_power_lag1
    row["ac_power_lag4"] = req.ac_power_lag4

    present = [c for c in FEATURE_COLS if c in row.columns]
    predicted_kw = float(np.clip(model.predict(row[present]), 0, None)[0])

    return ForecastResponse(
        timestamp=req.timestamp,
        predicted_kw=round(predicted_kw, 4),
        model_name=model_name,
    )


@app.get("/anomalies", response_model=AnomalyResponse)
def anomalies(
    limit: int = Query(default=200, le=5000),
    only_anomalies: bool = Query(default=True),
):
    """Return anomalous intervals from the test dataset."""
    adf = _state["anomaly_df"]
    if adf is None:
        raise HTTPException(503, "Data not loaded.")

    if only_anomalies:
        adf = adf[adf["is_anomaly"]]

    adf = adf.head(limit)

    records = [
        AnomalyRecord(
            timestamp=row["timestamp"],
            actual_kw=round(float(row["ac_power_kw"]), 4),
            predicted_kw=round(float(row["predicted_kw"]), 4),
            residual_kw=round(float(row["residual_kw"]), 4),
            residual_sigma=round(float(row.get("residual_sigma", 0) or 0), 3),
            lost_energy_kwh=round(float(row["lost_energy_kwh"]), 4),
            is_anomaly=bool(row["is_anomaly"]),
        )
        for _, row in adf.iterrows()
    ]

    total_lost = float((_state["anomaly_df"]["lost_energy_kwh"]).sum())

    return AnomalyResponse(
        total_anomalies=int(_state["anomaly_df"]["is_anomaly"].sum()),
        total_lost_kwh=round(total_lost, 2),
        records=records,
    )


@app.get("/events", response_model=EventsResponse)
def events(
    limit: int = Query(default=50, le=500),
    severity: str | None = Query(default=None, description="Filter by severity: low, medium, high"),
):
    """Return anomaly intervals grouped into contiguous events."""
    edf = _state["events_df"]
    if edf is None:
        raise HTTPException(503, "Event data not loaded. Run 'make train' first.")

    if severity:
        if severity not in ("low", "medium", "high"):
            raise HTTPException(400, "severity must be one of: low, medium, high")
        edf = edf[edf["severity"] == severity]

    edf = edf.head(limit)
    total_lost = float(_state["events_df"]["total_lost_kwh"].sum())

    event_records = [
        EventRecord(
            event_id=int(row["event_id"]),
            start_time=row["start_time"],
            end_time=row["end_time"],
            duration_minutes=int(row["duration_minutes"]),
            interval_count=int(row["interval_count"]),
            total_lost_kwh=round(float(row["total_lost_kwh"]), 3),
            max_residual_sigma=round(float(row["max_residual_sigma"]), 3),
            mean_actual_kw=round(float(row["mean_actual_kw"]), 4),
            mean_predicted_kw=round(float(row["mean_predicted_kw"]), 4),
            severity=row["severity"],
            explanation=str(row.get("explanation", "")),
            site_id=row.get("site_id"),
        )
        for _, row in edf.iterrows()
    ]

    return EventsResponse(
        total_events=len(_state["events_df"]),
        total_lost_kwh=round(total_lost, 2),
        events=event_records,
    )


@app.get("/explain", response_model=ExplainResponse)
def explain(
    timestamp: datetime = Query(..., description="Timestamp of the interval to explain (ISO 8601)"),
):
    """Return SHAP feature contributions for the model's prediction at a given timestamp.

    The timestamp must match a row in the test dataset (to 15-minute precision).
    Uses the best available model; returns shap_available=False if SHAP is unavailable.
    """
    adf = _state["anomaly_df"]
    if adf is None:
        raise HTTPException(503, "Data not loaded.")

    # Match to nearest 15-min timestamp in the test set
    ts = pd.Timestamp(timestamp)
    mask = adf["timestamp"] == ts
    if not mask.any():
        # Try ±1 minute tolerance for float-timestamp issues
        mask = (adf["timestamp"] - ts).abs() <= pd.Timedelta("1min")
    if not mask.any():
        raise HTTPException(
            404,
            f"Timestamp {timestamp} not found in test dataset. "
            "Available range: "
            f"{adf['timestamp'].min().isoformat()} – {adf['timestamp'].max().isoformat()}",
        )

    row_df = build_features(adf[mask].head(1).copy())
    present = [c for c in FEATURE_COLS if c in row_df.columns]
    X_row = row_df[present]

    model_name = _state["best_model_name"]
    model = _state["models"].get(model_name)
    if model is None:
        raise HTTPException(503, "Model not loaded.")

    predicted_kw = float(np.clip(model.predict(X_row), 0, None)[0])

    # Attempt SHAP explanation
    try:
        from gridguard.explainability.shap_explain import explain_anomaly

        shap_df = explain_anomaly(model, X_row, top_n=len(present))
        contributors = [
            ExplainContributor(
                feature=r["feature"],
                feature_value=round(float(r["feature_value"]), 4),
                shap_value=round(float(r["shap_value"]), 4),
                direction="positive" if r["shap_value"] >= 0 else "negative",
            )
            for _, r in shap_df.iterrows()
        ]
        shap_available = True
    except Exception as exc:
        logger.warning("SHAP explanation failed: %s", exc)
        # Fallback: XGBoost feature importances as a proxy
        contributors = []
        shap_available = False
        if hasattr(model, "feature_importances_"):
            importances = model.feature_importances_
            for feat, imp in sorted(zip(present, importances), key=lambda x: -abs(x[1])):
                val = float(X_row[feat].iloc[0])
                contributors.append(
                    ExplainContributor(
                        feature=feat,
                        feature_value=round(val, 4),
                        shap_value=round(float(imp), 6),
                        direction="positive",
                    )
                )

    return ExplainResponse(
        timestamp=ts,
        predicted_kw=round(predicted_kw, 4),
        contributors=contributors[:10],
        model_name=model_name,
        shap_available=shap_available,
    )


@app.get("/sites", response_model=SitesResponse)
def sites_endpoint():
    """Return all configured DMV sites with geospatial metadata.

    Useful for building fleet map views or filtering dashboard data by site.
    Capacities and coordinates are approximate estimates from public records.
    """
    from gridguard.sites.registry import load_sites

    sites_dict = load_sites()
    records = [
        SiteRecord(
            site_id=s.site_id,
            name=s.name,
            region=s.region,
            latitude=s.latitude,
            longitude=s.longitude,
            capacity_kw=s.capacity_kw,
            notes=s.notes,
        )
        for s in sites_dict.values()
    ]
    return SitesResponse(sites=records, total=len(records))


@app.get("/metrics", response_model=MetricsResponse)
def metrics():
    """Return performance metrics for all trained models."""
    mdf = _state["metrics_df"]
    if mdf is None:
        raise HTTPException(503, "Metrics not computed. Run 'make train' first.")

    model_metrics = [
        ModelMetrics(
            model=row["model"],
            mae_kw=row["mae_kw"],
            rmse_kw=row["rmse_kw"],
            mape_pct=row["mape_pct"],
            r2=row["r2"],
        )
        for _, row in mdf.iterrows()
    ]
    return MetricsResponse(
        models=model_metrics,
        best_model=_state["best_model_name"],
    )
